<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class JobPostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('jobPosts')->insert([
            'id' => '1',
            'title' => 'IT Consultant',
            'organisation' => 'IBM',
            'estSalary' => '100000',
            'email' => 's3599721@student.rmit.edu.au',
            'state' => 'VIC',
            'city' => 'Melbourne',
            'minExp' => 4,
            'minEdu' => 2,
            'java' => 1,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 1,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 1,
            'macOS' => 0,
            'linux' => 1,
            'android' => 1,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 0,
            'adobe' => 1,
            'cloud' => 0,
            'description' => 'Information and Data are some of the most important organizational assets in today’s businesses. As an IT Consultant, you will be a key advisor for IBM’s clients, analyzing business requirements to design and implement the best security solutions for their needs. You will apply your technical skills to find the balance between enabling and securing the client\'s organization with the cognitive solutions that are making IBM the fastest growing enterprise security business in the world.',
            'created_at' => '2019-09-14 14:50:05',
            'updated_at' => '2019-09-14 14:50:05',
            'employer_id' => 2,
            'company_name' => "SilentRunner",
        ]);

        DB::table('jobPosts')->insert([
            'id' => '2',
            'title' => 'Java API Developer',
            'organisation' => 'Techadon',
            'estSalary' => '500',
            'email' => 'techadon@gmail.com',
            'state' => 'VIC',
            'city' => 'Melbourne',
            'minExp' => 0,
            'minEdu' => 4,
            'java' => 1,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 0,
            'html' => 0,
            'css' => 0,
            'python' => 0,
            'javascript' => 0,
            'sql' => 0,
            'unix' => 0,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 0,
            'macOS' => 0,
            'linux' => 0,
            'bash' => 0,
            'ciscoSystems' => 0,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'android' => 0,
            'powershell' => 0,
            'rust' => 0,
            'iOS' => 0,
            'adobe' => 1,
            'cloud' => 0,
            'description' => '• Should be involved in design and development of Enterprise Software Systems built on Java and J2EE technologies.
• Should have design and development in Core Java, JSP/Servlet, JSF, Spring Boot, Spring Core, Spring MVC, Struts, Hibernate and developing web service or rest services
• Working with full stack platforms like Openshift, Kafka and Java Messaging Concepts. (JMS, MQ)
• Should have programming and Continuous integration: Build automation using Github, ANT, Maven, Jenkins, code quality analysis using SonarQube, and Python and R knowledge.',
            'created_at' => '2019-09-14 14:50:05',
            'updated_at' => '2019-09-14 14:50:05',
            'employer_id' => 1,
            'company_name' => "Group54",
        ]);

        DB::table('jobPosts')->insert([
            'id' => '3',
            'title' => 'Data Center Administrator',
            'organisation' => 'Atlassian',
            'estSalary' => '100000',
            'email' => 'arealemail@gmail.com',
            'state' => 'VIC',
            'city' => 'Melbourne',
            'minExp' => 4,
            'minEdu' => 2,
            'java' => 1,
            'c' => 0,
            'csharp' => 1,
            'cplus' => 1,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 1,
            'windowsServer' => 1,
            'macOS' => 1,
            'linux' => 1,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 1,
            'android' => 1,
            'adobe' => 1,
            'cloud' => 1,
            'description' => 'A data center administrator (DCA) is an experienced information technology (IT) professional who is responsible for overseeing data center operations. Because DCAs are in charge of business-critical systems, they need to have an in-depth knowledge about everything that occurs in the data center, including infrastructure design, operations and lifecycle management for physical and virtual data center assets.',
            'created_at' => '2019-09-14 14:50:05',
            'updated_at' => '2019-09-14 14:50:05',
            'employer_id' => 1,
            'company_name' => "Group54",
        ]);

        DB::table('jobPosts')->insert([
            'id' => '4',
            'title' => 'IT Systems Administrator',
            'organisation' => 'HOBAN Recruitment',
            'estSalary' => '78000',
            'email' => 'notfake@gmail.com',
            'state' => 'NSW',
            'city' => 'Sydney',
            'minExp' => 3,
            'minEdu' => 1,
            'java' => 1,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 1,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 0,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 0,
            'windowsOld' => 1,
            'windowsServer' => 0,
            'macOS' => 0,
            'linux' => 0,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 1,
            'android' => 1,
            'adobe' => 1,
            'cloud' => 1,
            'description' => 'Working with a passionate, professional team, the IT System administrator assists the council in 2nd and  3rd level Support and help manage the server systems and Council Applications.
                              Your background will be with IT, having worked previously as a System Analyst. This local council prides itself on efficient services and integrity of its IT Systems. You are someone who brings stability and previous skills to reach outcomes.',
            'created_at' => '2019-09-14 14:50:05',
            'updated_at' => '2019-09-14 14:50:05',
            'employer_id' => 2,
            'company_name' => "SilentRunner",
        ]);

        DB::table('jobPosts')->insert([
            'id' => '5',
            'title' => 'Junior IT Support Admin',
            'organisation' => 'Atlassian',
            'estSalary' => '56000',
            'email' => 'iswearthisisreal@gmail.com',
            'state' => 'TAS',
            'city' => 'Hobart',
            'minExp' => 0,
            'minEdu' => 10,
            'java' => 1,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'sql' => 0,
            'unix' => 0,
            'windows10' => 0,
            'windows7' => 1,
            'windowsOld' => 1,
            'windowsServer' => 0,
            'macOS' => 0,
            'linux' => 0,
            'bash' => 0,
            'ciscoSystems' => 0,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 0,
            'android' => 1,
            'adobe' => 0,
            'cloud' => 0,
            'description' => 'The successful applicant will possess the following:

Ability to work independently or as part of a team
Good Communication Skills
Ability to work under pressure and maintain accuracy (Great attention to detail)
Eager to learn new technology 
Essential Skills for this role:

Extensive knowledge with Microsoft Office 365 suite (Microsoft Teams, Share point, Word,
Good IT troubleshooting skills
Demonstrated IT support experience (remote and on-site)
Experience in building and supporting hardware (Windows and MAC OS/environment)
IT or related tertiary education',
            'created_at' => '2019-09-14 14:50:05',
            'updated_at' => '2019-09-14 14:50:05',
            'employer_id' => 1,
            'company_name' => "Group54",
        ]);
    }
}
