<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'id' => '1',
            'name' => 'Connor',
            'email' => 's3599721@student.rmit.edu.au',
            'password' => bcrypt('password'),
            'state' => 'VIC',
            'city' => 'Melbourne',
            'experience' => 1,
            'education' => 1,
            'java' => 1,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 1,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 1,
            'macOS' => 0,
            'linux' => 1,
            'android' => 0,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 0,
            'adobe' => 1,
            'cloud' => 0,
        ]);

        DB::table('users')->insert([
            'id' => '2',
            'name' => 'Anthony',
            'email' => 's3605187@student.rmit.edu.au',
            'password' => bcrypt('password'),
            'state' => 'VIC',
            'city' => 'Melbourne',
            'experience' => 2,
            'education' => 1,
            'java' => 1,
            'c' => 0,
            'csharp'=> 0,
            'cplus' => 0,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 1,
            'javascript' => 0,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 0,
            'macOS' => 0,
            'linux' => 1,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'android' => 1,
            'powershell' => 0,
            'rust' => 0,
            'iOS' => 1,
            'adobe' => 0,
            'cloud' => 1,
        ]);

        DB::table('users')->insert([
            'id' => '3',
            'name' => 'Jeff',
            'email' => 's3571902@student.rmit.edu.au',
            'password' => bcrypt('password'),
            'state' => 'VIC',
            'city' => 'Melbourne',
            'experience' => 2,
            'education' => 2,
            'java' => 1,
            'c' => 0,
            'csharp'=> 0,
            'cplus' => 1,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 1,
            'macOS' => 0,
            'linux' => 1,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'android' => 0,
            'rust' => 1,
            'iOS' => 0,
            'adobe' => 1,
            'cloud' => 1,
        ]);

        DB::table('users')->insert([
            'id' => '4',
            'name' => 'Jason',
            'email' => 's3591176@student.rmit.edu.au',
            'password' => bcrypt('password'),
            'state' => 'VIC',
            'city' => 'Melbourne',
            'experience' => 2,
            'education' => 3,
            'java' => 0,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'android' => 0,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 1,
            'macOS' => 0,
            'linux' => 0,
            'bash' => 1,
            'ciscoSystems' => 1,
            'microsoftOffice' => 1,
            'ruby' => 0,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 0,
            'adobe' => 1,
            'cloud' => 1,
        ]);

        DB::table('users')->insert([
            'id' => '5',
            'name' => 'Jeremy',
            'email' => 's345333@student.rmit.edu.au',
            'password' => bcrypt('password'),
            'state' => 'VIC',
            'city' => 'Ballarat',
            'experience' => 1,
            'education' => 6,
            'java' => 0,
            'c' => 1,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'android' => 0,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 1,
            'macOS' => 0,
            'linux' => 0,
            'bash' => 1,
            'ciscoSystems' => 0,
            'microsoftOffice' => 1,
            'ruby' => 1,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 0,
            'adobe' => 1,
            'cloud' => 1,
        ]);

        DB::table('users')->insert([
            'id' => '6',
            'name' => 'Ray',
            'email' => 's365544@student.rmit.edu.au',
            'password' => bcrypt('password'),
            'state' => 'NSW',
            'city' => 'Sydney',
            'experience' => 4,
            'education' => 3,
            'java' => 0,
            'c' => 1,
            'csharp' => 0,
            'cplus' => 1,
            'php' => 1,
            'html' => 1,
            'css' => 1,
            'python' => 0,
            'javascript' => 1,
            'android' => 1,
            'sql' => 1,
            'unix' => 1,
            'windows10' => 1,
            'windows7' => 1,
            'windowsOld' => 0,
            'windowsServer' => 1,
            'macOS' => 0,
            'linux' => 0,
            'bash' => 1,
            'ciscoSystems' => 0,
            'microsoftOffice' => 1,
            'ruby' => 1,
            'powershell' => 1,
            'rust' => 0,
            'iOS' => 1,
            'adobe' => 1,
            'cloud' => 1,
        ]);

    }
}
